import os
import pandas as pd
import kagglehub
from IPython.display import display
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import lightgbm as lgb
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
import fitz

#------------------
### DATA COLLECTION
#------------------

# Excel file
df_excel = pd.read_excel("/Users/constancehenin/Desktop/M2/U6 - Data Project Management/AI and Big Data Project/preprocessed-50k.xlsx")

print(df_excel.sample(5))

# Format the dataframe
df = pd.DataFrame(df_excel)

# Excel
df.info()
df["generated"].value_counts()

# Sample the whole dataset to run faster
df_sample = df.sample(n=20000, random_state=123).reset_index(drop=True)

df_sample.info()
print(df_sample.sample(n=10))
df_sample["generated"].value_counts()

#-----------------
### MODEL PLANNING
#-----------------

# Fix the target and the features for modeling

X_text = df_sample["text"]
y = df_sample["generated"]

## Data (text) vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=20000,
    stop_words='english',
    lowercase=True,
    ngram_range=(1, 3),
    min_df=5,
    token_pattern=r"(?u)\b\w+\b|[^\w\s]"  # keeps words + ponctuation
)
X_text = [str(x) for x in X_text]
X = vectorizer.fit_transform(X_text)

# Split df into two sets (training & testing)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=123, stratify=y
)

# Model development 
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

#--------------
### APPLICATION
#--------------

st.title("AI Text Detector")

#TEXT
st.markdown("Detects whether a text has been generated by an AI or written by a human")
user_input = st.text_area("✍️ Enter a text here", height=200)

if st.button("Predict"):
    if user_input.strip() == "":
        st.warning("Thank you for writing a text")
    else:
        # Transformer le texte
        X_user = vectorizer.transform([user_input])
        pred = model.predict(X_user)[0]
        proba = model.predict_proba(X_user)[0][1]

        if pred == 1:
            st.success(f"This text is probably generated by an **IA**. (AI Score :{proba:.0%})")
        else:
            st.info(f"This text was probably written by a **Human**. (AI Score :{proba:.0%})")

#PDF
pdf_file = st.file_uploader("Upload a PDF file", type=["pdf"])
if pdf_file is not None:
    # Read and extract text from PDF
    with fitz.open(stream=pdf_file.read(), filetype="pdf") as doc:
        text = ""
        for page in doc:
            text += page.get_text()

    st.text_area("Extracted PDF Text", text, height=200)

    if st.button("PDF Predict"):
        if text.strip() == "":
            st.warning("❗ No readable text found in PDF.")
        else:
            X_pdf = vectorizer.transform([text])
            pred_pdf = model.predict(X_pdf)[0]
            proba_pdf = model.predict_proba(X_pdf)[0][1]

            if pred_pdf == 1:
                st.success(f"This PDF is probably generated by **AI**. (AI Score: {proba_pdf:.0%})")
            else:
                st.info(f"This PDF is probably written by a **human**. (AI Score: {proba_pdf:.0%})")        

